import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';
import 'dart:math' as math;
import 'package:crypto/crypto.dart';
import 'vault_data.dart';
import 'vault_screens.dart';
import 'qr_scanner_screen.dart';
import 'pin_unlock_screen.dart' show PinScreen, PinScreenMode;
import 'seed_phrase_restore_screen.dart';
import 'crypto/bip39.dart';
import 'screens/password_add_screen.dart';
import 'screens/api_key_add_screen.dart';
import 'screens/recovery_codes_add_screen.dart';
import 'screens/secure_note_add_screen.dart';
import 'screens/auth_screen.dart';
import 'screens/security_setup_screen.dart';
import 'services/preference_service.dart';
